### ISSUE TITLE
wrong times

### ISSUE THREAD

**Issue by horstderheld** [solarissmoke/php-moon-phase#11]
compared to the wikipedia lunar calender your moon phases for 2016 are always a bit off (~30 to 50 minutes). That results in wrong dates in some cases.

**Comment by solarissmoke** [comment]
I'm not sure which Wikipedia calendar you are referring to?

**Comment by horstderheld** [comment]
https://commons.wikimedia.org/wiki/File:Calendario_Lunar_2016.png
tables from the German wiki: https://de.wikipedia.org/wiki/Mondphasen_(Tabelle)

But now I get why the times are wrong.. Or better can't be right. For the Calculation you're using the average Lunar cycle time, but every Lunar cycle is a bit different, what results in the different times.

**Comment by solarissmoke** [comment]
I'm not sure what you mean about average timing...

In any case, it seems like those calendars are wrong. You can compare the times they have given to those published by NASA (http://eclipse.gsfc.nasa.gov/SKYCAL/SKYCAL.html?cal=2016#skycal or http://www.space.com/18880-moon-phases.html) or the US Naval Observatory (http://aa.usno.navy.mil/data/docs/MoonPhase.php) - these are very accurate.

This library should give you results very close (within a few seconds) to the times published by NASA.

**Comment by horstderheld** [comment]
$synmonth = 29.53058868;	// Synodic month (new Moon to new Moon)
that's the average time... 
But it changes a lot (http://eclipse.gsfc.nasa.gov/SEhelp/moonorbit.html), so we can't calculate it exactly, only within few hours..

**Comment by solarissmoke** [comment]
The error introduced by that is very small - nowhere near the 20-50 minutes you are reporting. Here is the output of `MoonPhase.php` for the New Moon for the next few months:

```
Wed, 09 Mar 16 01:55:59 
Thu, 07 Apr 16 11:25:20
Fri, 06 May 16 19:31:18 
Sun, 05 Jun 16 03:01:45
Mon, 04 Jul 16 11:03:23
Tue, 02 Aug 16 20:46:40
Thu, 01 Sep 16 09:04:59
Sat, 01 Oct 16 00:13:14
````
Compare it to data from NASA:

```
Mar. 9 	01:54
Apr. 7 	11:24
May 6 	19:30
Jun. 5 	03:00
Jul. 4 	11:01 	
Aug. 2 	20:45
Sep. 1 	09:03
Oct. 1 	00:12
```

The maximum error is about 2 minutes.

I am pretty sure the times in that Wikipedia calendar are wrong.
