### ISSUE TITLE
PHP Moon phase code needed

### ISSUE THREAD

**Issue by stleary** [solarissmoke/php-moon-phase#13]
Hello,
Any objection if I fork this project to use in a WordPress plugin? I am in need of Moon phase data written in PHP. Will of course credit your work in the GitHub project and plugin page.
Thanks!
Sean
https://github.com/stleary/stars-at-night
https://wordpress.org/plugins/stars-at-night/

**Comment by solarissmoke** [comment]
No objection - go ahead!
