### ISSUE TITLE
Add Images

### ISSUE THREAD

**Issue by StarkRavingZA** [solarissmoke/php-moon-phase#15]
Would be great if this could be expanded to pick an image from a local set of images and display the phase as an image along with the information currently provided.

**Comment by spacecactus** [comment]
I had that up on my website for a while, moonworm.net. Just took the phase_name and added a .jpg to the end of it, which pulled it from an image directory to be displayed. 

moonpic.php
> 
> include 'MoonPhase.php';
> $moon = new Solaris\MoonPhase();
> $PhaseName = $moon->phase_name();
> header ("Content-type: image/jpg");
> readfile("../images/$PhaseName.jpg");

**Comment by solarissmoke** [comment]
I don't foresee adding images to this library in the future - think this is best left for projects that use the core of this library to implement in a way that works for their own use case.
