### ISSUE TITLE
Custom time

### ISSUE THREAD

**Issue by RyanBlundell** [solarissmoke/php-moon-phase#21]
How can we set custom times? In the old version I did this, however after upgrading to the latest version it doesnt seem to be working anymore and uses the server timestamp

$moon = new Solaris\MoonPhase(strtotime(date('Y-m-d 12:00').' +1 day'));
$moon = new Solaris\MoonPhase(strtotime(date('Y-m-d 12:00').' +2 day'));
$moon = new Solaris\MoonPhase(strtotime(date('Y-m-d 12:00').' +3 day'));

**Comment by solarissmoke** [comment]
Thanks for reporting this - it was broken in the last set of changes. Should be fixed now on master.
