### ISSUE TITLE
Incorrect date format

### ISSUE THREAD

**Issue by novaidea** [solarissmoke/php-moon-phase#22]
Eample: The next first quarter is at 12:00:00, 24 Nov -4713

Bad date in:
get_phase('first_quarter')
get_phase('next_first_quarter')

Thanks,
Keep up the good work

**Comment by SuN-80** [comment]
It happens because phasehunt() returns a null $jdate on line 334. 
Could not find why :/

It would be great if dev could fix this!

**Comment by minigopher17** [comment]
To fix it, after line 268, add `$apcor = true;` so then the block looks like this:

```
			if ($phase < 0.5)
			{
				$pt += 0.0028 - 0.0004 * cos(deg2rad($m)) + 0.0003 * cos(deg2rad($mprime));
				$apcor = true;
			}
			else
			{
				$pt += -0.0028 + 0.0004 * cos(deg2rad($m)) - 0.0003 * cos(deg2rad($mprime));
				$apcor = true;
			}
```

**Comment by SuN-80** [comment]
Thanks a lot it worked like a charm!
