### ISSUE TITLE
Error on MoonPhase.php?

### ISSUE THREAD

**Issue by splobsterman** [solarissmoke/php-moon-phase#26]

**Comment by splobsterman** [comment]
Any pointers as to what might be causing this?

`PHP Parse error:  syntax error, unexpected ':', expecting ';' or '{' in /public_html/tests/Solaris/MoonPhase.php on line 149
`
Here's my test code (from your README):

`<?php
// create an instance of the class, and use the current time

include 'Solaris/MoonPhase.php';
$moon = new Solaris\MoonPhase();
$age = round($moon->get('age'), 1);
$stage = $moon->phase() < 0.5 ? 'waxing' : 'waning';
$distance = round($moon->get('distance'), 2);
$next = gmdate('G:i:s, j M Y', $moon->get_phase('next_new_moon'));
echo "The moon is currently $age days old, and is therefore $stage. ";
echo "It is $distance km from the centre of the Earth. ";
echo "The next new moon is at $next.";
?>`

With thanks

**Comment by solarissmoke** [comment]
The latest version of the library requires PHP 7 or higher - looks like you are using an older version of PHP.

**Comment by splobsterman** [comment]
Thank you Samir
