### ISSUE TITLE
Different Time Zone

### ISSUE THREAD

**Issue by injainja** [solarissmoke/php-moon-phase#27]
I am living in UTC+1 in Winter and UTC+2 in Summer. Is there a way to set different timezones? Because atm all the outputs are 1 hour off :-(
And is there a way to set different locations?

**Comment by solarissmoke** [comment]
> Is there a way to set different timezones?

The class returns timestamps in UTC - it's up to you to display/render them in whatever time zone you are working in. The documentation for PHP's [date utils](https://www.php.net/manual/en/book.datetime.php) explains how to set the default timezone.

> And is there a way to set different locations?

No - the moon phase is not dependent on location on Earth.

**Comment by injainja** [comment]
Ah, I just needed to set
date_default_timezone_set('Europe/Berlin');
and to replace gmdate(...) with date(...) 
THnx
