### ISSUE TITLE
Get zodiac name in which the Moon is

### ISSUE THREAD

**Issue by keretlen** [solarissmoke/php-moon-phase#30]
I would like to extend your class and find the zodiac name in which the Moon is.
You can see here
https://www.rhythmofnature.net/gardener-calendar-november-2019
on the right side there are the zodiac signs like Capricorn, Aquarius, etc.
Is it possible to do somehow?

**Comment by solarissmoke** [comment]
Sorry, this isn't something that this package can do.

**Comment by angelocala94** [comment]
See #33
