### ISSUE TITLE
Notice:  Undefined offset: 8 in MoonPhase.php on line 343

### ISSUE THREAD

**Issue by allanlaal** [solarissmoke/php-moon-phase#36]
Notice:  Undefined offset: 8 in MoonPhase.php on line 343

**Comment by allanlaal** [comment]
..which is:

			return $names[ floor( ( $this->phase + 0.0625 ) * 8 ) ];


shouldn't this line have a modulus operation instead?:

				return $names[ floor( ( $this->phase + 0.0625 ) % 8 ) ];

**Comment by allanlaal** [comment]
@evert-mouw do your moon phases work?

**Comment by solarissmoke** [comment]
I'm afraid I no longer have time/inclination to maintain this repository, and to review new features/issues, so I'm closing this. If anyone is interested in taking over maintenance of the package, please get in touch with me (link in the readme).
