### ISSUE TITLE
Returns past phases for some timestamps

### ISSUE THREAD

**Issue by vvendigo** [solarissmoke/php-moon-phase#6]
```php
$date = new DateTime('2016-08-02 22:50:09');
$moon = new Solaris\MoonPhase($date->getTimestamp());
$timeFmt = 'Y-m-d H:i:s';

echo 'TS '.$date->getTimestamp()."\n";
echo 'Now '.date($timeFmt, $date->getTimestamp())."\n";
echo 'FQ '.date($timeFmt, $moon->first_quarter())."\n";
echo 'FM '.date($timeFmt, $moon->full_moon())."\n";
echo 'LQ '.date($timeFmt, $moon->last_quarter())."\n";
echo 'NM '.date($timeFmt, $moon->new_moon())."\n";
echo 'NNM '.date($timeFmt, $moon->next_new_moon())."\n";
```

---- Output: -------------------------------
TS 1470171009
Now 2016-08-02 22:50:09
FQ 2016-07-12 02:52:41
FM 2016-07-20 00:59:36
LQ 2016-07-27 01:02:35
NM 2016-07-04 13:03:23
NNM 2016-08-02 22:46:40

**Comment by vvendigo** [comment]
I used next_new_moon() to iterate moon phases calendar. It works fine, except some TS. Another example is October 2009.

I thought it's just matter of some odd second, but difference is quite big.

**Comment by solarissmoke** [comment]
Thanks - I have just pushed a change which should fix this. 

I need to get around to writing some tests for this library.
