### ISSUE TITLE
give the moon phase for a month

### ISSUE THREAD

**Issue by pioc92** [solarissmoke/php-moon-phase#7]
Hi, thnak you for this script.

 it would be nice if you could give all the phases of the moon for a month.
We enter the year and the month and the script give us an array with all the dates and phases.

**Comment by jlcolon13** [comment]
I know phase_name isn't as accurate but this may work for you on all phases of the month.
<pre>
$stage = $moon->phase() < 0.5 ? 'Waxing' : 'Waning';
$stage .= $moon->phase() > 0.01 && $moon->phase() < 0.24 ||
          $moon->phase() > 0.74 && $moon->phase() < 0.99
          ? ' Crescent' : ' Gibbous';
</pre>
As for the second request I think you can multiply the phase by the currently given phase. (not tested).

**Comment by solarissmoke** [comment]
I'm afraid I no longer have time/inclination to maintain this repository, and to review new features/issues, so I'm closing this. If anyone is interested in taking over maintenance of the package, please get in touch with me (link in the readme).
