### ISSUE TITLE
Full Moon Name (enhancement)

### ISSUE THREAD

**Issue by jlcolon13** [solarissmoke/php-moon-phase#9]
This would be a nice enhancement: The Name of the Full Moon for that Month.
<pre>
function full_moon_name($month) {
        /* Array keyed start at 1 for January */
        $monthly_names = array( 1 => 'Moon after Yule','Snow Moon','Sap Moon','Grass Moon','Planting Moon','Honey Moon','Thunder Moon','Grain Moon','Fruit Moon','Hunter\'s Moon','Frosty Moon','Moon before Yule' );
        $month = empty($month) ? date(F) : $month;
        return $monthly_names[date(n, strtotime($month))];
    }
$full = gmdate('G:i:s, j M Y', $moon->next_full_moon());
echo "This month's full moon is called " . $moon->full_moon_name() . ".<br/>\n";
echo "The next full moon is at $full called " . $moon->full_moon_name($full) . ".<br/>\n";
</pre>
This month's full moon is called Fruit Moon.
The next full moon is at 12:05:59, 27 Oct 2015 called Hunter's Moon.

**Comment by solarissmoke** [comment]
This seems to be a very specific nomenclature - as such I'm not sure should be part of the core moon phase class (many other cultures/traditions have their own nomenclature which are no more/less relevant than this one). It should be quite easy to add this layer on top of the class, as you are probably doing already?

**Comment by jlcolon13** [comment]
You're absolutely right, thank you greatly.

**Comment by injainja** [comment]
That helped me a lot for doing a script for a shamanic calendar. Thnx.
